Argument error of cu_gabor_wavefront
The “cu_gabor_wavefront” function is being passed a Matrix{Float32} type argument, but the function expects a CuArray{Float32, 2} type argument, causing the error.

Solved this by converting after loading the image.

Here is the error I got when I ran the code before the modification.

ERROR: LoadError: MethodError: no method matching cu_gabor_wavefront(::Matrix{Float32})

Closest candidates are:
  cu_gabor_wavefront(::CuArray{Float32, 2})
   @ ParticleHolography ~/.julia/packages/ParticleHolography/2EWun/src/holofunc.jl:81